carnet/urls.py
from django.conf.urls import url
from . import views

app_name = 'carnet'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'ajouter-fiche/(?P<slug>[\w-]+)/$', views.ajouter_fiche, name='ajouter_fiche'),
    url(r'modifier-fiche/(?P<fiche_id>\d+)/$', views.modifier_fiche, name='modifier_fiche'),
    url(r'supprimer-fiche/(?P<fiche_id>\d+)/$', views.supprimer_fiche, name='supprimer_fiche')
]

projet/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^recette/', include('recette.urls')),
    url(r'^carnet/', include('carnet.urls')),
    url(r'^utilisateurs/', include('utilisateurs.urls')),
    url(r'^admin/', admin.site.urls),
]

recette/urls.py
from django.conf.urls import url
from . import views

app_name = 'recette'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^voir/(?P<slug>[\w-]+)/$', views.voir, name='voir'),
    url(r'^voir/(?P<slug>[\w-]+)/noter$', views.noter, name='noter'),
    url(r'^voir/(?P<slug>[\w-]+)/commenter$', views.commenter, name='commenter'),
    url(r'^voir/(?P<slug>[\w-]+)/modifier$', views.modifier, name='modifier'),
    url(r'^voir/(?P<slug>[\w-]+)/supprimer$', views.supprimer, name='supprimer'),
    url(r'^rechercher', views.rechercher, name='rechercher'),
    url(r'^ajouter', views.ajouter, name='ajouter'),
    url(r'^aleatoire', views.aleatoire, name='aleatoire')
]

carnet/models.py
from django.contrib.auth.models import User
from django.db import models

from recette.models import Recette


class Fiche(models.Model):
    utilisateur = models.ForeignKey(User, related_name='fiche_user')
    recette = models.ForeignKey(Recette, related_name='fiche_recette')
    remarque = models.TextField(null=True, blank=True)

carnet/forms.py
from django import forms

from carnet.models import Fiche


class FicheForm(forms.ModelForm):
    class Meta:
        model = Fiche
        exclude = ['utilisateur', 'recette']

carnet/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404, redirect

from carnet.forms import FicheForm
from carnet.models import Fiche
from recette.models import Recette


NB_FICHES_PAR_PAGE = 3


@login_required(login_url='utilisateurs:connexion')
def index(request):
    fiches = Fiche.objects.all()
    fiches = paginer(request.GET.get('page'), fiches, NB_FICHES_PAR_PAGE)

    return render(request, 'index.html', {
        'fiches': fiches
    })


@login_required(login_url='utilisateurs:connexion')
def ajouter_fiche(request, slug):
    recette = get_object_or_404(Recette, slug=slug)

    if request.method == "POST":
        formulaire = FicheForm(request.POST)
        if formulaire.is_valid():
            post = request.POST

            if post and 'remarque' in post:
                fiche = Fiche(utilisateur=request.user, recette=recette, remarque=post['remarque'])
            else:
                fiche = Fiche(utilisateur=request.user, recette=recette, remarque='')

            fiche.save()
            return redirect('carnet:index')
    else:
        formulaire = FicheForm()

    return render(request, 'fiche/ajouter.html', {
        'formulaire': formulaire,
        'recette': recette
    })

@login_required(login_url='utilisateurs:connexion')
def modifier_fiche(request, fiche_id):
    fiche = get_object_or_404(Fiche, id=fiche_id)

    if request.user != fiche.utilisateur:
        raise PermissionDenied

    formulaire = FicheForm(request.POST or None, instance=fiche)

    if request.POST and formulaire.is_valid():
        formulaire.save()
        return redirect('carnet:index')

    return render(request, 'fiche/modifier.html', {
        'fiche': fiche,
        'formulaire': formulaire
    })

@login_required(login_url='utilisateurs:connexion')
def supprimer_fiche(request, fiche_id):
    fiche = get_object_or_404(Fiche, id=int(fiche_id))

    # Si on est l'utilisateur de cette fiche
    if request.user != fiche.utilisateur:
        raise PermissionDenied

    fiche.delete()

    return redirect('carnet:index')


def paginer(page, objects, nb):
    paginator = Paginator(objects, nb)

    try:
        objects = paginator.page(page)
    except PageNotAnInteger:
        objects = paginator.page(1)
    except EmptyPage:
        objects = paginator.page(paginator.num_pages)

    return objects

carnet/templates/index.html
{% extends '_base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block nav_carnet %} class="active"{% endblock %}
{% block title %}Mon carnet{% endblock %}
{% block jumbotron_titre %}Carnet{% endblock %}
{% block jumbotron_contenu %}
    Consultez ici vos recettes préférées et gérez les !
{% endblock %}
{% block jumbotron_nav %}
	<li><a href="{% url 'recette:index' %}">Accueil</a></li>
	<li class="active">Mon carnet</li>
{% endblock %}

{% block contenu %}
    <div class="row">
         <ul class="pagination">
            {% if fiches.has_previous %}
                <li><a href="?page={{ fiches.previous_page_number }}">Précédent</a></li>
            {% endif %}

            <li class="disabled"><a href="#">Page {{ fiches.number }} sur {{ fiches.paginator.num_pages }}</a></li>

            {% if fiches.has_next %}
                <li><a href="?page={{ fiches.next_page_number }}">Suivant</a></li>
            {% endif %}
        </ul>
    </div>
    <div class="row">
        <div class="blog">
            {% for fiche in fiches %}
                <div class="col-sm-4">
                    <div class="blog-item">
                        <img class="img-responsive img-blog" src="/{{ STATIC_URL }}{{ fiche.recette.photo.url }}" alt=""/>
                        <div class="blog-content">
                            <h3>{{ fiche.recette.titre }}</h3>
                            <div class="entry-meta">
                                Note :
                                {% if fiche.recette.nb_notes == 0 %}
                                    Aucune pour le moment.
                                {% else %}
                                    {{ fiche.recette.note }}
                                {% endif %}
                                <br />{{ fiche.recette.nb_commentaires }} commentaire{% if fiche.recette.nb_commentaires > 1 %}s{% endif %}
                                {% if fiche.remarque != '' %}
                                    <p><strong>Remarque personelle</strong> : {{ fiche.remarque }}</p>
                                {% endif %}
                            </div>
                            <a class="btn btn-default" href="{% url 'recette:voir' fiche.recette.slug %}">Consulter <i class="icon-angle-right"></i></a>
                            <a class="btn btn-primary" href="{% url 'carnet:modifier_fiche' fiche.id %}">Modifier</i></a>
                            <a class="btn btn-danger" href="{% url 'carnet:supprimer_fiche' fiche.id %}">Supprimer</i></a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="row">
         <ul class="pagination">
            {% if fiches.has_previous %}
                <li><a href="?page={{ fiches.previous_page_number }}">Précédent</a></li>
            {% endif %}

            <li class="disabled"><a href="#">Page {{ fiches.number }} sur {{ fiches.paginator.num_pages }}</a></li>

            {% if fiches.has_next %}
                <li><a href="?page={{ fiches.next_page_number }}">Suivant</a></li>
            {% endif %}
        </ul>
    </div>
{% endblock %}