carnet/urls.py
from django.conf.urls import url
from . import views

app_name = 'carnet'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'ajouter-fiche/(?P<slug>[\w-]+)/$', views.ajouter_fiche, name='ajouter_fiche'),
    url(r'modifier-fiche/(?P<fiche_id>\d+)/$', views.modifier_fiche, name='modifier_fiche'),
    url(r'supprimer-fiche/(?P<fiche_id>\d+)/$', views.supprimer_fiche, name='supprimer_fiche')
]

projet/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^recette/', include('recette.urls')),
    url(r'^carnet/', include('carnet.urls')),
    url(r'^utilisateurs/', include('utilisateurs.urls')),
    url(r'^admin/', admin.site.urls),
]

recette/urls.py
from django.conf.urls import url
from . import views

app_name = 'recette'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^voir/(?P<slug>[\w-]+)/$', views.voir, name='voir'),
    url(r'^voir/(?P<slug>[\w-]+)/noter$', views.noter, name='noter'),
    url(r'^voir/(?P<slug>[\w-]+)/commenter$', views.commenter, name='commenter'),
    url(r'^voir/(?P<slug>[\w-]+)/modifier$', views.modifier, name='modifier'),
    url(r'^voir/(?P<slug>[\w-]+)/supprimer$', views.supprimer, name='supprimer'),
    url(r'^rechercher', views.rechercher, name='rechercher'),
    url(r'^ajouter', views.ajouter, name='ajouter'),
    url(r'^aleatoire', views.aleatoire, name='aleatoire')
]

utilisateurs/urls.py
from django.conf.urls import url
from . import views

app_name = 'utilisateurs'
urlpatterns = [
   url(r'^connexion', views.connexion, name='connexion'),
   url(r'^inscription', views.inscription, name='inscription'),
   url(r'^deconnexion', views.deconnexion, name='deconnexion')
]

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="Rudy de Visscher, Gautier Rivière">
        <title>{% block title %}Recette InShape{% endblock %}</title>
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
        <link href="{% static 'css/animate.css' %}" rel="stylesheet">
        <link href="{% static 'css/main.css' %}" rel="stylesheet">
        <!--[if lt IE 9]>
        <script src="{% static 'js/html5shiv.js' %}"></script>
        <script src="{% static 'js/respond.min.js' %}"></script>
        <![endif]-->
    </head><!--/head-->
    <body>
        <header class="navbar navbar-inverse navbar-fixed-top wet-asphalt" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'recette:index' %}">InShape</a>
                </div>
                <div class="collapse navbar-collapse">
                    <form method="GET" action="{% url 'recette:rechercher' %}" class="navbar-form navbar-nav navbar-right">
                        <input type="hidden" name="ordre" value="titre" />
                        <div class="form-group">
                            <input class="form-control" type="text" name="recette_rechercher"
                                   {% if request.GET.recette_rechercher %}value="{{ request.GET.recette_rechercher }}"{% endif %}/>
                        </div>
                        <button type="submit" class="btn btn-primary">Rechercher</button>
                    </form>
                    <ul class="nav navbar-nav navbar-right">
                        <li{% block nav_accueil %}{% endblock %}><a href="{% url 'recette:index' %}">Accueil</a></li>
                        <li class="dropdown {% block nav_menu %}{% endblock %}">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu <i class="icon-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                <h6 class="dropdown-header">Type de plat</h6>
                                <li><a href="{% url 'recette:rechercher' %}?ordre=titre&amp;recette_rechercher=&amp;tri=type&amp;choix=0">Entrée</a></li>
                                <li><a href="{% url 'recette:rechercher' %}?ordre=titre&amp;recette_rechercher=&amp;tri=type&amp;choix=1">Plat</a></li>
                                <li><a href="{% url 'recette:rechercher' %}?ordre=titre&amp;recette_rechercher=&amp;tri=type&amp;choix=2">Dessert</a></li>
                                <li role="separator" class="divider"></li>
                                <h6 class="dropdown-header">Difficulté</h6>
                                <li><a href="{% url 'recette:rechercher' %}?ordre=titre&amp;recette_rechercher=&amp;tri=difficulte&amp;choix=0">Facile</a></li>
                                <li><a href="{% url 'recette:rechercher' %}?ordre=titre&amp;recette_rechercher=&amp;tri=difficulte&amp;choix=1">Moyen</a></li>
                                <li><a href="{% url 'recette:rechercher' %}?ordre=titre&amp;recette_rechercher=&amp;tri=difficulte&amp;choix=2">Difficile</a></li>
                            </ul>
                        </li>
                        <li{% block nav_carnet %}{% endblock %}><a href="{% url 'carnet:index' %}">Mon carnet</a></li>
                        <li><a href="{% url 'recette:aleatoire' %}">Recette aléatoire</a></li>
                        <li{% block nav_ajouter_recette %}{% endblock %}><a href="{% url 'recette:ajouter' %}">Ajouter recette</a></li>
                        <li class="dropdown {% block nav_utilisateurs %}{% endblock %}">
                            {% if user.is_authenticated %}
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ request.user.username }} <i class="icon-angle-down"></i></a>
                            {% else %}
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Utilisateurs <i class="icon-angle-down"></i></a>
                            {% endif %}
                            <ul class="dropdown-menu">
                                {% if user.is_authenticated %}
                                    <li><a href="{% url 'utilisateurs:deconnexion' %}">Déconnexion</a></li>
                                {% else %}
                                    <li><a href="{% url 'utilisateurs:connexion' %}">Connexion</a></li>
                                    <li><a href="{% url 'utilisateurs:inscription' %}">Inscription</a></li>
                                {% endif %}
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </header><!--/header-->

        {% if erreur and erreur != '' %}
            <section id="alert" class="alizarin">
                <div class="container" style="text-align: center">
                    {{ erreur }}
                    <button type="button" class="close" id="closeAlert">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </section>
        {% endif %}

        <section id="title" class="emerald">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <h1>{% block jumbotron_titre %}Titre de la page{% endblock %}</h1>
                        <p>{% block jumbotron_contenu %}Pellentesque habitant morbi tristique senectus et netus et malesuada{% endblock %}</p>
                    </div>
                    <div class="col-sm-6">
                        <ul class="breadcrumb pull-right">
                            {% block jumbotron_nav %}{% endblock %}
                        </ul>
                    </div>
                </div>
            </div>
        </section><!--/#title-->

        <section class="container">
            {% block contenu %}
            {% endblock %}
        </section>

        <footer id="footer" class="midnight-blue">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        &copy; 2017 All Rights Reserved. Project Django with M. Debureaux
                    </div>
                    <div class="col-sm-6">
                        <ul class="pull-right">
                            <li><a id="gototop" class="gototop" href="#">Remonter en haut de la page <i class="icon-chevron-up"></i></a></li><!--#gototop-->
                        </ul>
                    </div>
                </div>
            </div>
        </footer><!--/#footer-->

        {% block javascripts %}
            <script src="{% static 'js/jquery.js' %}"></script>
            <script src="{% static 'js/bootstrap.min.js' %}"></script>
            <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
            <script src="{% static 'js/main.js' %}"></script>
        {% endblock %}
    </body>
</html>