carnet/urls.py
from django.conf.urls import url
from . import views

app_name = 'carnet'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'ajouter-fiche/(?P<slug>[\w-]+)/$', views.ajouter_fiche, name='ajouter_fiche'),
    url(r'modifier-fiche/(?P<fiche_id>\d+)/$', views.modifier_fiche, name='modifier_fiche'),
    url(r'supprimer-fiche/(?P<fiche_id>\d+)/$', views.supprimer_fiche, name='supprimer_fiche')
]

projet/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^recette/', include('recette.urls')),
    url(r'^carnet/', include('carnet.urls')),
    url(r'^utilisateurs/', include('utilisateurs.urls')),
    url(r'^admin/', admin.site.urls),
]

recette/urls.py
from django.conf.urls import url
from . import views

app_name = 'recette'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^voir/(?P<slug>[\w-]+)/$', views.voir, name='voir'),
    url(r'^voir/(?P<slug>[\w-]+)/noter$', views.noter, name='noter'),
    url(r'^voir/(?P<slug>[\w-]+)/commenter$', views.commenter, name='commenter'),
    url(r'^voir/(?P<slug>[\w-]+)/modifier$', views.modifier, name='modifier'),
    url(r'^voir/(?P<slug>[\w-]+)/supprimer$', views.supprimer, name='supprimer'),
    url(r'^rechercher', views.rechercher, name='rechercher'),
    url(r'^ajouter', views.ajouter, name='ajouter'),
    url(r'^aleatoire', views.aleatoire, name='aleatoire')
]

recette/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
import os
from uuid import uuid4


def path_and_rename(instance, filename):
    upload_to = 'static/images/recette/'
    ext = filename.split('.')[-1]

    filename = '{}.{}'.format(uuid4().hex, ext)
    return os.path.join(upload_to, filename)


class Recette(models.Model):
    TYPES = (
        (0, 'Entrée'),
        (1, 'Plat'),
        (2, 'Dessert')
    )

    DIFFICULTES = (
        (0, 'Facile'),
        (1, 'Moyen'),
        (2, 'Difficile')
    )

    titre = models.CharField(max_length=100)
    type = models.SmallIntegerField(choices=TYPES, default=0)
    difficulte = models.SmallIntegerField(choices=DIFFICULTES, default=0)
    cout = models.FloatField()
    photo = models.ImageField(upload_to=path_and_rename, default='static/images/recette/defaut.png', null=True)
    temps_preparation = models.IntegerField()
    temps_cuisson = models.IntegerField()
    temps_repos = models.IntegerField(null=True, blank=True, default=0)
    ingredients = models.TextField()
    etapes = models.TextField()
    nb_notes = models.IntegerField(default=0)
    note = models.FloatField()
    slug = models.SlugField(unique=True)
    utilisateur = models.ForeignKey(User, related_name='recette_user', null=True)
    nb_commentaires = models.IntegerField(default=0)
    date_ajout = models.DateTimeField(null=True, blank=True)
    date_modification = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.titre

    def save(self, *args, **kwargs):
        self.slug = slugify(self.titre)

        super(Recette, self).save(*args, **kwargs)


class Note(models.Model):
    NOTES = (
        (0, 0),
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5)
    )

    note = models.SmallIntegerField(choices=NOTES, default=5)
    utilisateur = models.ForeignKey(User, related_name='note_user')
    recette = models.ForeignKey(Recette, related_name='note_recette')

    def __str__(self):
        return self.note.__str__()


class Commentaire(models.Model):
    utilisateur = models.ForeignKey(User, related_name='commentaire_user')
    recette = models.ForeignKey(Recette, related_name='commentaire_recette')
    commentaire = models.TextField()
    date = models.DateTimeField()

    def __str__(self):
        return self.commentaire

recette/forms.py
from django import forms
from recette.models import Recette


# Constantes
NOTE_MIN = 0
NOTE_MAX = 5


class RecetteForm(forms.ModelForm):
    class Meta:
        model = Recette
        exclude = ['nb_notes', 'note', 'slug', 'utilisateur', 'nb_commentaires']


class NoteForm(forms.Form):
    note = forms.IntegerField(min_value=NOTE_MIN, max_value=NOTE_MAX)


class CommentaireForm(forms.Form):
    commentaire = forms.CharField(widget=forms.Textarea)


class TriRechercheForm(forms.Form):
    ORDRES = (
        ('titre', 'Titre croissant'),
        ('-titre', 'Titre décroissant'),
        ('note', 'Note croissante'),
        ('-note', 'Note décroissante'),
        ('difficulte', 'Difficulté croissante'),
        ('-difficulte', 'Difficulté décroissante'),
        ('temps_preparation', 'Temps de préparation croissant'),
        ('-temps_preparation', 'Temps de préparation décroissant')
    )

    ordre = forms.ChoiceField(choices=ORDRES)

recette/views.py
from random import randint

from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.core.exceptions import PermissionDenied
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from datetime import datetime

from carnet.models import Fiche
from recette.forms import RecetteForm, NoteForm, CommentaireForm, TriRechercheForm
from recette.models import Recette, Note, Commentaire


# Constantes
NB_COMMENTAIRES_PAR_PAGE = 2
NB_RECETTES_PAR_PAGE = 3


def index(request):
    recettes = Recette.objects.all()

    recettes = paginer(request.GET.get('page'), recettes, NB_RECETTES_PAR_PAGE)

    return render(request, 'liste.html', {
        'recettes': recettes
    })


def voir(request, slug):
    recette = get_object_or_404(Recette, slug=slug)
    all_commentaires = Commentaire.objects.filter(recette=recette)
    a_vote = False
    a_ajouter_au_carnet = False

    commentaires = paginer(request.GET.get('page'), all_commentaires, NB_COMMENTAIRES_PAR_PAGE)

    # Formulaires
    formulaire_note = NoteForm()
    formulaire_commentaire = CommentaireForm()

    # Savoir si l'utilisateur a déjà voté ou non
    if request.user.is_authenticated and Note.objects.filter(recette=recette, utilisateur=request.user).exists():
        a_vote = True

    # Si l'utilisateur a déjà ajouté cette recette à son carnet ou non
    if request.user.is_authenticated and Fiche.objects.filter(utilisateur=request.user, recette=recette).exists():
        a_ajouter_au_carnet = True

    return render(request, 'voir.html', {
        'recette': recette,
        'commentaires': commentaires,
        'formulaire_note': formulaire_note,
        'formulaire_commentaire': formulaire_commentaire,
        'a_vote': a_vote,
        'a_ajouter_au_carnet': a_ajouter_au_carnet
    })


@login_required(login_url='utilisateurs:connexion')
def ajouter(request):
    erreur = ''
    if request.method == "POST":
        formulaire = RecetteForm(request.POST, request.FILES)
        if formulaire.is_valid():
            post = request.POST
            files = request.FILES

            if 'photo_recette' in files:
                photo = files['photo_recette']
            else:
                photo = ''

            if recette_est_correcte(post, photo):
                if not Recette.objects.filter(titre=post['titre']).exists():
                    recette = Recette(
                        titre=post['titre'],
                        type=post['type'],
                        difficulte=post['difficulte'],
                        cout=post['cout'],
                        photo=photo,
                        temps_preparation=post['temps_preparation'],
                        temps_cuisson=post['temps_cuisson'],
                        temps_repos=post['temps_repos'],
                        ingredients=post['ingredients'],
                        etapes=post['etapes'],
                        nb_notes=0,
                        note=0.0,
                        utilisateur=request.user,
                        nb_commentaires=0,
                        date_ajout=datetime.now()
                    )
                    recette.save()

                    return redirect('recette:index')
                else:
                    erreur = 'Une recette de ce titre existe déjà !'
            else:
                erreur = 'Tous les champs sont obligatoires !'
        else:
            erreur = 'Erreur dans le formulaire'
    else:
        formulaire = RecetteForm()

    return render(request, 'ajouter.html', {
        'formulaire': formulaire,
        'erreur': erreur
    })


@login_required(login_url='utilisateurs:connexion')
def modifier(request, slug):
    recette = get_object_or_404(Recette, slug=slug)

    if request.user != recette.utilisateur:
        raise PermissionDenied

    formulaire = RecetteForm(request.POST or None, instance=recette)

    if request.POST and formulaire.is_valid():
        recette.date_modification = datetime.now()
        formulaire.save()
        return redirect('recette:voir', slug=recette.slug)

    return render(request, 'modifier.html', {
        'recette': recette,
        'formulaire': formulaire
    })


@login_required(login_url='utilisateurs:connexion')
def supprimer(request, slug):
    recette = get_object_or_404(Recette, slug=slug)

    # Si on est l'auteur de la recette
    if request.user != recette.utilisateur:
        raise PermissionDenied

    recette.delete()

    return redirect('recette:index')


@login_required(login_url='utilisateurs:connexion')
def noter(request, slug):
    recette = get_object_or_404(Recette, slug=slug)

    # Un vote par utilisateur possible
    if not Note.objects.filter(recette=recette, utilisateur=request.user).exists():
        if request.method == "POST":
            post = request.POST
            note = Note(
                note=post['note'],
                utilisateur=request.user,
                recette=recette
            )
            note.save()

            # Calcul de la note moyenne
            notes = Note.objects.filter(recette_id=recette.id)
            recette.note = (recette.note + float(note.note)) / float(notes.count())
            recette.nb_notes += 1
            recette.save()

    return redirect('recette:voir', slug=recette.slug)


@login_required(login_url='utilisateurs:connexion')
def commenter(request, slug):
    recette = get_object_or_404(Recette, slug=slug)

    if request.method == "POST":
        post = request.POST
        commentaire = Commentaire(
            utilisateur=request.user,
            recette=recette,
            commentaire=post['commentaire'],
            date=datetime.now()
        )
        commentaire.save()

        # Mise à jour du nb de commentaires pour la recette
        recette.nb_commentaires += 1
        recette.save()

    return redirect('recette:voir', slug=recette.slug)


# TODO : adapter le formulaire pour trier aussi selon le type/difficulte
def rechercher(request):
    formulaire_tri = TriRechercheForm()

    if request.method == "GET":
        get = request.GET
        if get and 'recette_rechercher' in get and 'ordre' in get:
            critere = request.GET.get('recette_rechercher')
            ordre = get['ordre']
            if 'tri' in get and 'choix' in get:
                tri = get['tri']
                choix = get['choix']
                if tri == "type":
                    recettes = Recette.objects.filter((Q(titre__contains=critere) | Q(ingredients__contains=critere)), type=choix)
                elif tri == "difficulte":
                    recettes = Recette.objects.filter((Q(titre__contains=critere) | Q(ingredients__contains=critere)), difficulte=choix)
            else:
                recettes = Recette.objects.filter(Q(titre__contains=critere) | Q(ingredients__contains=critere))\
                    .order_by(ordre)

            return render(request, 'rechercher.html', {
                'recettes': recettes,
                'formulaire_tri': formulaire_tri,
                'critere': critere,
                'nb_recettes': recettes.count()
            })
        else:
            raise Http404("Erreur dans le formulaire de recherche")
    else:
        raise Http404("Erreur dans le formulaire de recherche")


def aleatoire(request):
    recette_trouve = False
    derniere_recette = Recette.objects.latest('id')
    max_id = int(derniere_recette.id)

    nombre_aleatoire = randint(1, max_id)
    while not recette_trouve:
        if Recette.objects.filter(pk=nombre_aleatoire).count() > 0:
            recette = Recette.objects.get(pk=nombre_aleatoire)
            recette_trouve = True

    all_commentaires = Commentaire.objects.filter(recette=recette)
    a_vote = False
    a_ajouter_au_carnet = False

    commentaires = paginer(request.GET.get('page'), all_commentaires, NB_COMMENTAIRES_PAR_PAGE)

    # Formulaires
    formulaire_note = NoteForm()
    formulaire_commentaire = CommentaireForm()

    # Savoir si l'utilisateur a déjà voté ou non
    if request.user.is_authenticated and Note.objects.filter(recette=recette, utilisateur=request.user).exists():
        a_vote = True

    # Si l'utilisateur a déjà ajouté cette recette à son carnet ou non
    if request.user.is_authenticated and Fiche.objects.filter(utilisateur=request.user, recette=recette).exists():
        a_ajouter_au_carnet = True

    return render(request, 'voir.html', {
        'recette': recette,
        'commentaires': commentaires,
        'formulaire_note': formulaire_note,
        'formulaire_commentaire': formulaire_commentaire,
        'a_vote': a_vote,
        'a_ajouter_au_carnet': a_ajouter_au_carnet
    })


def recette_est_correcte(post, photo):
    if (
        'titre' in post and
        'type' in post and
        'difficulte' in post and
        'cout' in post and
        photo != '' and
        'temps_preparation' in post and
        'temps_cuisson' in post and
        'temps_repos' in post and
        'ingredients' in post and
        'etapes' in post
    ):
        return True
    else:
        return False


def paginer(page, objects, nb):
    paginator = Paginator(objects, nb)

    try:
        objects = paginator.page(page)
    except PageNotAnInteger:
        objects = paginator.page(1)
    except EmptyPage:
        objects = paginator.page(paginator.num_pages)

    return objects

recette/templates/ajouter.html
{% extends '_base.html' %}
{% load widget_tweaks %}
{% block title %}Ajouter une recette{% endblock %}
{% block jumbotron_titre %}Ajouter une recette{% endblock %}
{% block jumbotron_contenu %}Ajoutez dès maintenant votre recette pour en faire profiter tout le monde !{% endblock %}
{% block jumbotron_nav %}
	<li><a href="{% url 'recette:index' %}">Accueil</a></li>
	<li class="active">Ajouter une recette</li>
{% endblock %}

{% block nav_ajouter_recette %} class="active"{% endblock %}

{% block contenu %}
    <div class="panel panel-default col-sm-8 col-sm-offset-2"">
    <div class="panel-body">
    <div class="">
        <form method="post" action="{% url 'recette:ajouter' %}" enctype="multipart/form-data">
            <div class="form-group">
                {% render_field formulaire.titre class+='form-control' placeholder='Titre' %}
            </div>

            <div class="form-group">
                {{ formulaire.type.label_tag }}
                {% render_field formulaire.type class+='form-control' placeholder='Type' %}
            </div>

            <div class="form-group">
                {{ formulaire.difficulte.label_tag }}
                {% render_field formulaire.difficulte class+='form-control' placeholder='Difficulté' %}
            </div>

            <div class="form-group">
                {% render_field formulaire.cout class+='form-control' placeholder='Coût' %}
            </div>

            <div class="form-group">
                {{ formulaire.photo.label_tag }}
                <input id="photo" type="file" name="photo_recette"/>
            </div>

            <div class="form-group">
                {% render_field formulaire.temps_preparation class+='form-control' placeholder='Temps de préparation (en min)' %}
            </div>

            <div class="form-group">
                {% render_field formulaire.temps_cuisson class+='form-control' placeholder='Temps de cuissons (en min)' %}
            </div>

            <div class="form-group">
                {% render_field formulaire.temps_repos class+='form-control' placeholder='Temps de repos (en min)' %}
            </div>

            <div class="form-group">
                {% render_field formulaire.ingredients class+='form-control' placeholder='Ingrédients' %}
            </div>

            <div class="form-group">
                {% render_field formulaire.etapes class+='form-control' placeholder='Etapes' %}
            </div>

            <button type="submit" class="btn btn-block btn-primary btn-lg">Ajouter</button>

            {% csrf_token %}
        </form>
    </div></div></div>
{% endblock %}

recette/templates/liste.html
{% extends '_base.html' %}

{% block title %}Accueil recettes{% endblock %}
{% block nav_accueil %} class="active"{% endblock %}
{% block jumbotron_titre %}Accueil{% endblock %}
{% block jumbotron_contenu %}Bienvenue sur la page d'accueil ! Ici vous pourrez consulter les dernières recettes ajoutés{% endblock %}
{% block jumbotron_nav %}
	<li><a href="{% url 'recette:index' %}">Accueil</a></li>
	<li class="active">Dernières recette</li>
{% endblock %}

{% block contenu %}
    <div class="row">
         <ul class="pagination">
            {% if recettes.has_previous %}
                <li><a href="?page={{ recettes.previous_page_number }}">Précédent</a></li>
            {% endif %}

            <li class="disabled"><a href="#">Page {{ recettes.number }} sur {{ recettes.paginator.num_pages }}</a></li>

            {% if recettes.has_next %}
                <li><a href="?page={{ recettes.next_page_number }}">Suivant</a></li>
            {% endif %}
        </ul>
    </div>

    <div class="row">
        <div class="blog">
        {% for recette in recettes %}
            <div class="col-sm-4">
                <div class="blog-item">
                    <img class="img-responsive img-blog" src="/{{ STATIC_URL }}{{ recette.photo.url }}" alt=""/>
                    <div class="blog-content">
                        <h3>{{ recette.titre }}</h3>
                        <div class="entry-meta">
                            Note :
                            {% if recette.nb_notes == 0 %}
                                Aucune pour le moment.
                            {% else %}
                                {{ recette.note }}
                            {% endif %}
                            <br />{{ recette.nb_commentaires }} commentaire{% if recette.nb_commentaires > 1 %}s{% endif %}
                        </div>
                        <a class="btn btn-default" href="{% url 'recette:voir' recette.slug %}">Consulter <i class="icon-angle-right"></i></a>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>

    <div class="row">
         <ul class="pagination">
            {% if recettes.has_previous %}
                <li><a href="?page={{ recettes.previous_page_number }}">Précédent</a></li>
            {% endif %}

            <li class="disabled"><a href="#">Page {{ recettes.number }} sur {{ recettes.paginator.num_pages }}</a></li>

            {% if recettes.has_next %}
                <li><a href="?page={{ recettes.next_page_number }}">Suivant</a></li>
            {% endif %}
        </ul>
    </div>

{% endblock %}

recette/templates/menu.html
{% extends '_base.html' %}

{% block title %}Menu{% endblock %}
{% block nav_menu %}active{% endblock %}
{% block jumbotron_titre %}Menu{% endblock %}
{% block jumbotron_contenu %}Lisez les recettes par type ou par difficulté !{% endblock %}
{% block jumbotron_nav %}
	<li><a href="{% url 'recette:index' %}">Accueil</a></li>
	<li class="active">Menu</li>
{% endblock %}

{% block contenu %}
        <div class="blog">
        {% if nb_recettes > 0 %}{% for recette in recettes %}
            <div class="col-sm-4">
                <div class="blog-item">
                    <img class="img-responsive img-blog" src="/{{ STATIC_URL }}{{ recette.photo.url }}" alt=""/>
                    <div class="blog-content">
                        <h3>{{ recette.titre }}</h3>
                        <div class="entry-meta">
                            Note :
                            {% if recette.nb_notes == 0 %}
                                Aucune pour le moment.
                            {% else %}
                                {{ recette.note }}
                            {% endif %}
                            <br />{{ recette.nb_commentaires }} commentaire{% if recette.nb_commentaires > 1 %}s{% endif %}
                        </div>
                        <a class="btn btn-default" href="{% url 'recette:voir' recette.slug %}">Consulter <i class="icon-angle-right"></i></a>
                    </div>
                </div>
            </div>
        {% endfor %}{% else %}
            <p>Aucune recette pour le moment.</p>
        {% endif %}
        </div>

{% endblock %}

recette/templates/modifier.html
{% extends '_base.html' %}
{% load widget_tweaks %}
{% block title %}Modifier une recette{% endblock %}
{% block jumbotron_titre %}Modifier une recette{% endblock %}
{% block jumbotron_contenu %}Mettez à jour comme vous le souhaitez votre recette.{% endblock %}
{% block jumbotron_nav %}
	<li><a href="{% url 'recette:index' %}">Accueil</a></li>
	<li class="active">Modifier une recette</li>
{% endblock %}

{% block nav_ajouter_recette %} class="active"{% endblock %}

{% block contenu %}
    <div class="panel panel-default col-sm-8 col-sm-offset-2"">
    <div class="panel-body">
    <div class="">
        <form method="post" action="{% url 'recette:modifier' recette.slug %}" onsubmit="return confirm('Voulez-vous vraiment modifier cette recette ?')" enctype="multipart/form-data">
            <div class="form-group">
                {% render_field formulaire.titre class+='form-control' placeholder='Titre' %}
            </div>

            <div class="form-group">
                {{ formulaire.type.label_tag }}
                {% render_field formulaire.type class+='form-control' placeholder='Type' %}
            </div>

            <div class="form-group">
                {{ formulaire.difficulte.label_tag }}
                {% render_field formulaire.difficulte class+='form-control' placeholder='Difficulté' %}
            </div>

            <div class="form-group">
                {% render_field formulaire.cout class+='form-control' placeholder='Coût' %}
            </div>

            <div class="form-group">
                {{ formulaire.photo.label_tag }}
                {% render_field formulaire.photo placeholder='Photo' %}
            </div>

            <div class="form-group">
                {% render_field formulaire.temps_preparation class+='form-control' placeholder='Temps de préparation (en min)' %}
            </div>

            <div class="form-group">
                {% render_field formulaire.temps_cuisson class+='form-control' placeholder='Temps de cuissons (en min)' %}
            </div>

            <div class="form-group">
                {% render_field formulaire.temps_repos class+='form-control' placeholder='Temps de repos (en min)' %}
            </div>

            <div class="form-group">
                {% render_field formulaire.ingredients class+='form-control' placeholder='Ingrédients' %}
            </div>

            <div class="form-group">
                {% render_field formulaire.etapes class+='form-control' placeholder='Etapes' %}
            </div>

            <button type="submit" class="btn btn-block btn-primary btn-lg">Modifier</button>

            {% csrf_token %}
        </form>
    </div></div></div>
{% endblock %}

recette/templates/voir.html
{% extends '_base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Consulter une recette - {{ recette.titre }}{% endblock %}
{% block jumbotron_titre %}{{ recette.titre}}{% endblock %}
{% block jumbotron_contenu %}
    Proposé par {{ recette.utilisateur.username }} le {{ recette.date_ajout }}
    {% if recette.date_modification %}
    (dernière modification le {{ recette.date_modification }})
    {% endif %}
{% endblock %}
{% block jumbotron_nav %}
	<li><a href="{% url 'recette:index' %}">Accueil</a></li>
	<li class="active">Consulter une recette</li>
{% endblock %}

{% block contenu %}
    <div class="row">
        <div class="col-sm-4">
            <p><img src="/{{ STATIC_URL }}{{ recette.photo.url }}" alt="{{ recette.titre }}" class="img-rounded img-responsive" /></p>
            <div class="panel panel-default">
                <div class="panel-heading">INGREDIENTS</div>
                <div class="panel-body">
                    {{ recette.ingredients|linebreaks }}
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">NOTE ATTRIBUE</div>
                <div class="panel-body">
                    {{ recette.note }} / 5
                    {% if not user.is_authenticated %}
                        <p>Vous devez être connecté pour voter !</p>
                    {% elif a_vote %}
                        <p>Vous avez déjà voté pour cette recette !</p>
                    {% else %}
                        <p>
                            <form method="post" action="{% url 'recette:noter' recette.slug %}">
                                <div class="form-group">
                                    {% render_field formulaire_note.note class+='form-control' placeholder='Note /5' %}
                                </div>
                                <button class="btn btn-primary" type="submit">Noter</button>
                                {% csrf_token %}
                            </form>
                        </p>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-sm-8">
            {% if recette.date_modification %}
                <p>Dernière modification le {{ recette.date_modification }}</p>
            {% endif %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    {% if recette.type == 0 %}
                        <i class="icon-info"></i> Entrée
                    {% elif recette.type == 1 %}
                         <i class="icon-info"></i> Plat
                    {% else %}
                     <i class="icon-legal"></i> Dessert
                    {% endif %}&nbsp;&nbsp;
                    {% if recette.temps_preparation > 0 %}<i class="icon-time"></i> Préparation : {{ recette.temps_preparation }} min.{% endif %}
                    {% if recette.temps_cuisson > 0 %}<i class="icon-food"></i> Cuisson : {{ recette.temps_cuisson }} min. &nbsp;&nbsp;{% endif %}
                    {% if recette.temps_repos > 0 %}<i class="icon-adjust"></i> Repos : {{ recette.temps_repos }} min.&nbsp;{% endif %}
                    {% if recette.difficulte == 0 %}
                        <i class="icon-legal"></i> Difficulté : Facile
                    {% elif recette.difficulte == 1 %}
                         <i class="icon-legal"></i> Difficulté : Moyenne
                    {% else %}
                     <i class="icon-legal"></i> Difficulté : Difficile
                    {% endif %}&nbsp;&nbsp;
                    <i class="icon-eur"></i> {{ recette.cout }}
                </div>
                <div class="panel-body">
                    <h4>Etapes</h4>
                    {{ recette.etapes|linebreaks }}<br />
                </div>
            </div>
            {% if request.user %}
                <div class="panel panel-default">
                    <div class="panel-heading">Actions</div>
                    <div class="panel-body">
                        {% if a_ajouter_au_carnet %}
                            Cette recette est dans votre carnet
                        {% else %}
                            <a class="btn btn-default" href="{% url 'carnet:ajouter_fiche' recette.slug %}">Ajouter au carnet</a>
                        {% endif %}
                        {% if request.user == recette.utilisateur %}
                        <a href="{% url 'recette:modifier' recette.slug %}" class="btn btn-primary">Modifier</a>
                        <a class="btn btn-danger" onclick="return confirm('Etes-vous sûr de vouloir supprimer cette recette ?')" href="{% url 'recette:supprimer' recette.slug %}">Supprimer</a>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        </div>
    </div>

    <hr>

    <div class="panel panel-default">
        <div class="panel-heading"><strong>Commentaires</strong></div>
        <div class="panel-body">
        {% for commentaire in commentaires %}
            <div class="well">
                <strong>{{ commentaire.utilisateur.username }}</strong>
                <small>{{ commentaire.date }}</small>
                <p>{{ commentaire.commentaire|linebreaks }}</p>
            </div>
        {% endfor %}
        {% if recette.nb_commentaires == 0 %}
            <p>Aucun commentaire pour le moment. Soyez le premier à ajouter un commentaire !</p>
        {% endif %}
        </div>
    </div>

    {% if recette.nb_commentaires > 0 %}
    <ul class="pagination">
            {% if commentaires.has_previous %}
                <li><a href="?page={{ commentaires.previous_page_number }}">Précédent</a></li>
            {% endif %}

        <li class="disabled"><a href="#">Page {{ commentaires.number }} sur {{ commentaires.paginator.num_pages }}</a></li>

            {% if commentaires.has_next %}
                <li><a href="?page={{ commentaires.next_page_number }}">Suivant</a></li>
            {% endif %}
    </ul>
    {% endif %}

    <h3>Ajouter un commentaire</h3>
    {% if not user.is_authenticated %}
        <p>Vous devez être connecté pour pouvoir commenter cette recette !</p>
    {% else %}
        <form method="POST" action="{% url 'recette:commenter' recette.slug %}">
            <div class="form-group">{% render_field formulaire_commentaire.commentaire class+='form-control' placeholder='Votre commentaire ici !' %}</div>
            <button class="btn btn-primary" type="submit">Commenter</button>
            {% csrf_token %}
        </form>
    {% endif %}
{% endblock %}